/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nurse;

import Admin.DataBase;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

/**
 *
 * @author Sampath
 */
public class PatientAdmission extends javax.swing.JFrame {

    /**
     * Creates new form PatientAdmission
     */
    public PatientAdmission() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p_nic = new javax.swing.JTextField();
        wd_id = new javax.swing.JTextField();
        admt_dt = new com.toedter.calendar.JDateChooser();
        lv_dt = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        sbmt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        p_nm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p_id = new javax.swing.JTextField();
        dct_id = new javax.swing.JTextField();
        cnslt_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dlt = new javax.swing.JButton();
        updt = new javax.swing.JButton();
        srch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 222, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(613, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(613, 440));
        jPanel1.setPreferredSize(new java.awt.Dimension(613, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admission Forum");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Patient NIC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Admitted date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ward_id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, 30));

        p_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p_nicKeyTyped(evt);
            }
        });
        jPanel1.add(p_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 30));

        wd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wd_idActionPerformed(evt);
            }
        });
        jPanel1.add(wd_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 70, 30));
        jPanel1.add(admt_dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 120, 30));
        jPanel1.add(lv_dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Leaving date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, 30));

        sbmt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sbmt.setText("Submit");
        sbmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtActionPerformed(evt);
            }
        });
        jPanel1.add(sbmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 190, 40));

        jPanel2.setBackground(new java.awt.Color(227, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Patient name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 83, 30));
        jPanel2.add(p_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Search results");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Patient_id");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 30));
        jPanel2.add(p_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, 30));

        dct_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dct_idActionPerformed(evt);
            }
        });
        jPanel2.add(dct_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, 30));
        jPanel2.add(cnslt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 140, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("assigned consulant_id");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("confirmed doct ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 290, 210));

        dlt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dlt.setText("Delete");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        jPanel1.add(dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 190, 40));

        updt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updt.setText("Update / Leaving");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        jPanel1.add(updt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 190, 40));

        srch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        srch.setText("Search by NIC");
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });
        jPanel1.add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wd_idActionPerformed

    private void sbmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtActionPerformed
        // TODO add your handling code here:
        boolean chck=true;
        try {
            int wrd = Integer.valueOf(wd_id.getText());
        } catch (NumberFormatException e) {
            chck = false;
            JOptionPane.showMessageDialog(null, "Invalid data type..", "Submission...",JOptionPane.INFORMATION_MESSAGE);
        }
        
        if((chck) && p_nic.equals("")){
            JOptionPane.showMessageDialog(null, "You didn't enter patient nic..", "Validation error..",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                String p_id="", cnfm_doctId="";
                boolean check=true;
                Statement stat = DataBase.getStatement();
                ResultSet rs1 = stat.executeQuery("SELECT * FROM Patient WHERE nic_no='"+p_nic.getText()+"'");

                if(rs1.next()){                
                    p_id=rs1.getString("patient_id");
                    cnfm_doctId = rs1.getString("confirm_doct_id");
                }
                else{
                    JOptionPane.showMessageDialog(null, "This patient is not a registered one \n Register through Admin...", "Error..",JOptionPane.INFORMATION_MESSAGE);
                    check=false;                
                }
                if(check){
                    DateFormat dfm = new SimpleDateFormat("yyyy-MM-dd");
                    String dy1 = dfm.format(admt_dt.getDate());
                    //String dy2 = dfm.format(lv_dt.getDate());
                    stat.executeUpdate("INSERT INTO Admission(patient_id, ward_id, cnfm_doct_id, admit_dt) "
                            + "VALUES('"+p_id+"','"+wd_id.getText()+"','"+cnfm_doctId+"','"+dy1+"')");

                }                        
            } catch (Exception e) {
                e.printStackTrace();
            }

            p_nic.setText("");
            wd_id.setText("");
            admt_dt.setDateFormatString("");
        }
    }//GEN-LAST:event_sbmtActionPerformed

    private void dct_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dct_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dct_idActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        // TODO add your handling code here:
        try {
            String pId="", pNm="", cnfm_dctId="", ac_Id="", wdID="";
            Date a_Dt= new Date(2017-01-01), lvDt=new Date(2017-01-01);         
            boolean check_1=true;
            
            Statement stat = Admin.DataBase.getStatement();
            ResultSet rs1 = stat.executeQuery("SELECT * FROM Patient WHERE nic_no='"+p_nic.getText()+"'");
            
            if(rs1.next()){
                pId = rs1.getString("patient_id");
                pNm = rs1.getString("patient_fname")+" "+rs1.getString("patient_lname");
                cnfm_dctId = rs1.getString("confirm_doct_id");
                ac_Id = rs1.getString("assigned_consult_id");                                
            }
            else{
                check_1 = false;
                JOptionPane.showMessageDialog(null, "This patient is not registered", "Error...",JOptionPane.INFORMATION_MESSAGE);
            }                       
            
            if(check_1){
                ResultSet rs2 = stat.executeQuery("SELECT * FROM Admission WHERE patient_id='"+pId+"'");
                if(rs2.next()){
                    wdID = rs2.getString("ward_id");
                    a_Dt = rs2.getDate("admit_dt");
                    lvDt = rs2.getDate("leave_dt");                    
                }
            }
            p_id.setText(pId);
            p_nm.setText(pNm);
            admt_dt.setDate(a_Dt);
            wd_id.setText(wdID);
            lv_dt.setDate(lvDt);
            dct_id.setText(cnfm_dctId);
            cnslt_id.setText(ac_Id);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_srchActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
        boolean check=true, check2=true;
        String pID = "", admtID="";
        try {
            Statement stat = Admin.DataBase.getStatement();
            ResultSet rs1 = stat.executeQuery("SELECT * FROM Patient WHERE nic_no='"+p_nic.getText()+"'");
            if(rs1.next()){
                pID = rs1.getString("patient_id");
            }else{
                JOptionPane.showMessageDialog(null, "There is no patient with this nic no..", "Error...",JOptionPane.INFORMATION_MESSAGE);
                check=false;
            }
            
            if(check){
                ResultSet rs2 = stat.executeQuery("SELECT admt_id From Admission WHERE patient_id='"+pID+"'");
                if(rs2.next()){
                    admtID = rs2.getString(1);
                }else{
                    check2 = false;
                    JOptionPane.showMessageDialog(null, "This patient hasn't admitted yet..", "Error...",JOptionPane.INFORMATION_MESSAGE);
                }
                if(check2){
                    stat.executeUpdate("DELETE FROM Admission WHERE admt_id='"+admtID+"'");
                    JOptionPane.showMessageDialog(null, "Succesfully deleted that Admission", "Deletion...",JOptionPane.INFORMATION_MESSAGE);
                }
                
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_dltActionPerformed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        // TODO add your handling code here:
        String nic= p_nic.getText();
        boolean chck=true;
        try {
            int wrd = Integer.valueOf(wd_id.getText());
        } catch (NumberFormatException e) {
            chck = false;
            JOptionPane.showMessageDialog(null, "Invalid data type..", "Submission...",JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(chck && nic.equals("")){
            JOptionPane.showMessageDialog(null, "You didn't enter patient nic..", "Validation error..",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                boolean check=false;
                Statement stat = DataBase.getStatement();
                String pID="", admtID="";
                ResultSet rs1 = stat.executeQuery("SELECT * FROM Patient WHERE nic_no='"+nic+"'");

                if(rs1.next()){
                    check=true;
                    pID = rs1.getString("patient_id");
                }
                else{                
                    JOptionPane.showMessageDialog(null, "This patient is not registered.. \n Can't update...", "Error...",JOptionPane.INFORMATION_MESSAGE);
                }

                if(check){
                    ResultSet rs2 = stat.executeQuery("SELECT * FROM Admission WHERE patient_id="+pID);
                    boolean check2 = false;
                    if(rs2.next()){
                        admtID = rs2.getString("admt_id");
                        check2=true;
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "This patient is not a admitted one.. \n can't update... ", "Error...",JOptionPane.INFORMATION_MESSAGE);
                    }
                    if(check2){
                        DateFormat dfm = new SimpleDateFormat("yyyy-MM-dd");
                        
                        String dy2 = dfm.format(lv_dt.getDate());
                        stat.executeUpdate("UPDATE Admission "
                            + "SET ward_id='"+wd_id.getText()+"', leave_dt='"+dy2+"' "
                            + "WHERE admt_id='"+admtID+"'");
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            p_nic.setText("");
            wd_id.setText("");
            p_nm.setText("");
            p_id.setText("");
            dct_id.setText("");
            cnslt_id.setText("");
            admt_dt.setDateFormatString("");
            lv_dt.setDateFormatString("");
        }
    }//GEN-LAST:event_updtActionPerformed

    private void p_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_nicKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(p_nic.getText().length() == 10){
            evt.consume();
        }
    }//GEN-LAST:event_p_nicKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientAdmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientAdmission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser admt_dt;
    private javax.swing.JTextField cnslt_id;
    private javax.swing.JTextField dct_id;
    private javax.swing.JButton dlt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser lv_dt;
    private javax.swing.JTextField p_id;
    private javax.swing.JTextField p_nic;
    private javax.swing.JTextField p_nm;
    private javax.swing.JButton sbmt;
    private javax.swing.JButton srch;
    private javax.swing.JButton updt;
    private javax.swing.JTextField wd_id;
    // End of variables declaration//GEN-END:variables
}
