/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Admin.DataBase;
import javax.swing.JOptionPane;
import Admin.Selection_admin;

import java.sql.*;
/**
 *
 * @author Sampath
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pw1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        slct = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(538, 306));
        jPanel1.setMinimumSize(new java.awt.Dimension(538, 306));
        jPanel1.setPreferredSize(new java.awt.Dimension(538, 306));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 110, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, 40));

        pw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw1ActionPerformed(evt);
            }
        });
        jPanel1.add(pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 160, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USER LOGIN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 520, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("The Hospital Management System");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 40));

        slct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        slct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lahiru", "Doctor", "Nurse", "Attendance", "Cashier" }));
        slct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctActionPerformed(evt);
            }
        });
        jPanel1.add(slct, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/hsptl1.JPG"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 300));

        rst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rst.setText("Reset");
        rst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstActionPerformed(evt);
            }
        });
        jPanel1.add(rst, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        char pw[] = pw1.getPassword();
        String pw_1 = new String(pw);                   //get password you entered
        String un = slct.getSelectedItem().toString();  //get selected username
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs = stat.executeQuery("SELECT password FROM User_login WHERE username='"+un+"'");
            String passWrd="", userType="";
            
            while(rs.next()){
                passWrd = rs.getString(1);                  //get password saved in database
            }
            
            if(pw_1.equals(passWrd)){                       //check whether password is correct
                userType = un;                
                JOptionPane.showMessageDialog(null, "Succesfully logged in as "+un+"...", "<<<<  Login  >>>>",JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect password..", "Error..",JOptionPane.INFORMATION_MESSAGE);
            }
            
            if(userType.equals("Lahiru")){
                Selection_admin sa = new Selection_admin();
                sa.setVisible(true);
            }
            else if(userType.equals("Nurse")){
                Nurse.Selection_Nurse sn = new Nurse.Selection_Nurse();
                sn.setVisible(true);
            }
            else if(userType.equals("Doctor")){
                Doctor.SlctDoctor sa = new Doctor.SlctDoctor();
                sa.setVisible(true);
            }
            else if(userType.equals("Attendance")){
                Attendance_Admn.Attendance a = new Attendance_Admn.Attendance();
                a.setVisible(true);
            }
            else if(userType.equals("Cashier")){
                Cashier.payment cp = new Cashier.payment();
                cp.setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw1ActionPerformed

    private void slctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slctActionPerformed

    private void rstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstActionPerformed
        // TODO add your handling code here:
        pw1.setText("");
    }//GEN-LAST:event_rstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JButton rst;
    private javax.swing.JComboBox<String> slct;
    // End of variables declaration//GEN-END:variables
}
