/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Admin.DataBase;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sampath
 */
public class PasswordChange extends javax.swing.JFrame {

    /**
     * Creates new form PasswordChange
     */
    
    public PasswordChange() {
        initComponents();        
    }
    String userName="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nw = new javax.swing.JPasswordField();
        cur = new javax.swing.JPasswordField();
        rset = new javax.swing.JButton();
        chng = new javax.swing.JButton();
        unm = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 222, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(405, 267));
        jPanel1.setMinimumSize(new java.awt.Dimension(405, 267));
        jPanel1.setPreferredSize(new java.awt.Dimension(405, 267));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password Change");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 320, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("New Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("User name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 30));
        jPanel1.add(nw, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 30));
        jPanel1.add(cur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 180, 30));

        rset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rset.setText("Reset");
        rset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsetActionPerformed(evt);
            }
        });
        jPanel1.add(rset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 40));

        chng.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chng.setText("Change");
        chng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngActionPerformed(evt);
            }
        });
        jPanel1.add(chng, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, 40));

        unm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lahiru", "Nurse", "Doctor", "Attendance", "Cashier" }));
        jPanel1.add(unm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Current password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void rsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsetActionPerformed
        // TODO add your handling code here:
        cur.setText("");
        nw.setText("");
    }//GEN-LAST:event_rsetActionPerformed

    public void setUser(String u_name) {
        userName = u_name;
    }
    
    private void chngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngActionPerformed
        // TODO add your handling code here:
        try {
            if(userName.equals("")){
                userName = unm.getSelectedItem().toString();
            }
            Statement stat = DataBase.getStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM User_login WHERE username='"+userName+"'");
            String real_Current="", usrID = "";
            String current = new String(cur.getPassword());                 //current password that user supplied
            String newPW = new String(nw.getPassword());
            while(rs.next()){
                real_Current = rs.getString("password");
                usrID = rs.getString("lgn_id");
            }
            
            if(current.equals(real_Current)){                               //check whether previous password is matching
                
                JOptionPane.showMessageDialog(null, "Password changed successfully.. ", "Password Change..",JOptionPane.INFORMATION_MESSAGE);
                stat.executeUpdate("UPDATE User_login SET password='"+newPW+"' WHERE lgn_id='"+usrID+"'");
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Current password you entered is wrong.. "
                        + "\n You cant chnge login password", "Error..",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        cur.setText("");
        nw.setText("");
        this.dispose();
        
    }//GEN-LAST:event_chngActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chng;
    private javax.swing.JPasswordField cur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField nw;
    private javax.swing.JButton rset;
    private javax.swing.JComboBox<String> unm;
    // End of variables declaration//GEN-END:variables

    
}
