/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Attendance_Admn;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sampath
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        a_time = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        e_nic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lv_tm = new javax.swing.JTextField();
        sbmt = new javax.swing.JButton();
        updt = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        chng = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        attTable = new javax.swing.JTable();
        srch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mntSlct = new javax.swing.JComboBox<>();
        emp_nm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 222, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(930, 285));
        jPanel1.setMinimumSize(new java.awt.Dimension(930, 285));
        jPanel1.setPreferredSize(new java.awt.Dimension(930, 285));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daily Attendance");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 360, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NIC_no");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 30));
        jPanel1.add(a_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Arrived time");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 130, 30));

        e_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                e_nicKeyTyped(evt);
            }
        });
        jPanel1.add(e_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Leaving time");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, 30));
        jPanel1.add(lv_tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 150, 30));

        sbmt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sbmt.setText("Submit");
        sbmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtActionPerformed(evt);
            }
        });
        jPanel1.add(sbmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 90, 40));

        updt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updt.setText("Update");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        jPanel1.add(updt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 90, 40));

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 150, 40));

        chng.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chng.setText("Change Password");
        chng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngActionPerformed(evt);
            }
        });
        jPanel1.add(chng, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 40));

        attTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Attendence id", "Date", "Work-period"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(attTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 420, 160));

        srch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        srch.setText("Search by NIC");
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });
        jPanel1.add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 130, 50));

        jLabel3.setText("Choose Month");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 100, 30));

        jLabel6.setText("Employee name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 90, 30));

        mntSlct.setMaximumRowCount(12);
        mntSlct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel1.add(mntSlct, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 70, 30));

        emp_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_nmActionPerformed(evt);
            }
        });
        jPanel1.add(emp_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 160, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Set time");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 60, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sbmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtActionPerformed
        // TODO add your handling code here:
        String var_nic=e_nic.getText();
        String attndTime = a_time.getText();
        if(var_nic.equals("")){
            JOptionPane.showMessageDialog(null, "You didn't enter your nic..", "Validation error..",JOptionPane.INFORMATION_MESSAGE);
        }else{
            Controller.Attendence_Con ac = new Controller.Attendence_Con();

            ac.setAttendence(var_nic, attndTime);

            e_nic.setText("");
            a_time.setText("");
            lv_tm.setText("");
        }
    }//GEN-LAST:event_sbmtActionPerformed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        // TODO add your handling code here:Z
         
        String var_nic= e_nic.getText();
        String leftTime = lv_tm.getText();
        
        Controller.Attendence_Con ac = new Controller.Attendence_Con();        
        ac.setLeave(var_nic, leftTime);
        
        e_nic.setText("");
        a_time.setText("");
        lv_tm.setText("");
    }//GEN-LAST:event_updtActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JOptionPane.showMessageDialog(null, "Successfully loggedout by Attendence Admin...", "<<<<  Logout  >>>>",JOptionPane.INFORMATION_MESSAGE);
        Login.login l =new Login.login();
        l.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void chngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngActionPerformed
        // TODO add your handling code here:
        Login.PasswordChange pc = new Login.PasswordChange();
        pc.setUser("Attendance");
        pc.setVisible(true);
    }//GEN-LAST:event_chngActionPerformed

    private void emp_nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_nmActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        // TODO add your handling code here:
        try {
            String e_name="", empID="";
            boolean check=true;
            String mntNM = mntSlct.getSelectedItem().toString();
            
            Statement stat = Admin.DataBase.getStatement();
            ResultSet rs1 = stat.executeQuery("SELECT emp_id, emp_fname, emp_lname FROM Employee WHERE nic_no='"+e_nic.getText()+"'");
            if(rs1.next()){
                empID = rs1.getString(1);
                e_name = rs1.getString(2)+" "+rs1.getString(3);
            }else{
                check=false;
                JOptionPane.showMessageDialog(null, "No employee with given NIC no..", "Error..",JOptionPane.INFORMATION_MESSAGE);
            }
            
            if(check){
                emp_nm.setText(e_name);
                
                DefaultTableModel dtm = (DefaultTableModel)attTable.getModel();
                dtm.setRowCount(0);
                
                ResultSet rs2= stat.executeQuery("SELECT report_id, due_date, time_period FROM Daily_report WHERE emp_id='"+empID+"' AND month_name='"+mntNM+"'");
                
                while(rs2.next()){                    
                    dtm.addRow(new Object[]{rs2.getString(1),rs2.getDate(2),rs2.getString(3)});
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_srchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat dfm = new SimpleDateFormat("HH mm");        
        String tim = dfm.format(cal.getTime());
        a_time.setText(tim);
        lv_tm.setText(tim);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void e_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_e_nicKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(e_nic.getText().length() == 10){
            evt.consume();
        }
    }//GEN-LAST:event_e_nicKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_time;
    private javax.swing.JTable attTable;
    private javax.swing.JButton chng;
    private javax.swing.JTextField e_nic;
    private javax.swing.JTextField emp_nm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField lv_tm;
    private javax.swing.JComboBox<String> mntSlct;
    private javax.swing.JButton sbmt;
    private javax.swing.JButton srch;
    private javax.swing.JButton updt;
    // End of variables declaration//GEN-END:variables
}
