/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Sampath
 */
public class OtStaffReg extends javax.swing.JFrame {

    /**
     * Creates new form OtStaffReg
     */
    public OtStaffReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        otln = new javax.swing.JTextField();
        otfn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ot_addr = new javax.swing.JTextArea();
        ot_nic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ot_cntct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ml = new javax.swing.JRadioButton();
        fml = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        sbmt = new javax.swing.JButton();
        dlt = new javax.swing.JButton();
        updt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        srch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emid = new javax.swing.JTextField();
        otid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 222, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(633, 425));
        jPanel1.setMinimumSize(new java.awt.Dimension(633, 425));
        jPanel1.setPreferredSize(new java.awt.Dimension(633, 425));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Other Staff Registration Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 530, 40));
        jPanel1.add(otln, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 210, 30));
        jPanel1.add(otfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Gender");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 90, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 30));

        ot_addr.setColumns(20);
        ot_addr.setRows(5);
        jScrollPane1.setViewportView(ot_addr);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 210, 110));

        ot_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ot_nicKeyTyped(evt);
            }
        });
        jPanel1.add(ot_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("NIC no");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 30));
        jPanel1.add(ot_cntct, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, 30));

        ml.setBackground(new java.awt.Color(227, 222, 222));
        buttonGroup1.add(ml);
        ml.setText("Male");
        jPanel1.add(ml, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        fml.setBackground(new java.awt.Color(227, 222, 222));
        buttonGroup1.add(fml);
        fml.setText("Female");
        jPanel1.add(fml, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Contact no");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 120, 30));

        sbmt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sbmt.setText("Submit");
        sbmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtActionPerformed(evt);
            }
        });
        jPanel1.add(sbmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 80, 40));

        dlt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dlt.setText("Delete");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        jPanel1.add(dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 80, 40));

        updt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updt.setText("Update");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        jPanel1.add(updt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 80, 40));

        jPanel2.setBackground(new java.awt.Color(227, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        srch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        srch.setText("Search");
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });
        jPanel2.add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 30));

        jLabel8.setText("EmpId");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 30));

        jLabel9.setText("OtherStaff_Id");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 30));
        jPanel2.add(emid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 30));
        jPanel2.add(otid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 210, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sbmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtActionPerformed
        // TODO add your handling code here:
        String gndr = "";
        String nic = ot_nic.getText();
        String lname = otln.getText();
        String fname = otfn.getText();
        
        boolean checkValidity=true;
        
        if(nic.equals("") || lname.equals("") || fname.equals("")){
            checkValidity=false;                
        }
        
        if(ml.isSelected()){
            gndr = "Male";
        }else if(fml.isSelected()){
            gndr = "Female";
        }
        
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs2 = stat.executeQuery("SELECT * FROM Employee WHERE nic_no='"+nic+"'");
            if(rs2.next()){
                JOptionPane.showMessageDialog(null, "This employee is already entered to the system..", "Validation Error..",JOptionPane.INFORMATION_MESSAGE);
                checkValidity=false;
            }
            if(checkValidity){   
                
                stat.executeUpdate("INSERT INTO Employee (emp_fname, emp_lname, nic_no, gender, address, contact_no, career) "
                    + "VALUES('"+fname+"','"+lname+"','"+nic+"','"+gndr+"','"+ot_addr.getText()+"','"+ot_cntct.getText()+"','Other Staff')");
            }else{
                JOptionPane.showMessageDialog(null, "You have input data in wrong pattern", "Validation Error..",JOptionPane.INFORMATION_MESSAGE);
            }
            
            
        } catch (NumberFormatException e) {            
            JOptionPane.showMessageDialog(null, "Invalid data type..", "Error...",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
        String empid_1="";
        if(checkValidity){
            try {
                Statement stat2 = DataBase.getStatement();
                ResultSet empId = stat2.executeQuery("SELECT * FROM Employee WHERE emp_fname='"+otfn.getText()+"' AND emp_lname='"+otln.getText()+"'");

                while (empId.next()) {
                    empid_1= empId.getString("emp_id");

                }

                stat2.executeUpdate("INSERT INTO Maintenance_staff (emp_id, ms_fname, ms_lname) "
                        + "VALUES('"+empid_1+"','"+otfn.getText()+"','"+otln.getText()+"')");

            } catch (NumberFormatException e) {            
                JOptionPane.showMessageDialog(null, "Invalid data type..", "Error...",JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        otfn.setText("");
        otln.setText("");
        ot_addr.setText("");
        ot_cntct.setText(""); 
        emid.setText("");
        otid.setText("");
        ot_nic.setText("");
        
    }//GEN-LAST:event_sbmtActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
        String nic=ot_nic.getText(), empID="";
        boolean check=false;
        try {
            Statement stat =  DataBase.getStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM Employee WHERE nic_no='"+nic+"' AND career='Other Staff'");
            if(rs.next()){
                empID=rs.getString("emp_id");
                check=true;
            }
            else{
                JOptionPane.showMessageDialog(null, "You input invalid NIC no.. \n Cannot delete from maintenance employee..", "Error..",JOptionPane.INFORMATION_MESSAGE);
            }
            if(check){
                stat.executeUpdate("DELETE FROM Maintenance_staff WHERE emp_id='"+empID+"'");
                stat.executeUpdate("DELETE FROM Employee WHERE nic_no='"+nic+"'");
                JOptionPane.showMessageDialog(null, "Succesfully deleted from employee..", "Deletion..",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_dltActionPerformed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        // TODO add your handling code here:
        String gndr="";
        String fname=otfn.getText();
        String lname=otln.getText();
        String address=ot_addr.getText();
        String contact=ot_cntct.getText(); 
        String empID=emid.getText();
        String msID = otid.getText();
        String msNIC = ot_nic.getText();
        if(ml.isSelected()){
            gndr="Male";
        }else if(fml.isSelected()){
            gndr="Female";
        }
        
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM Employee WHERE nic_no='"+msNIC+"' AND career='Other Staff'");
            if(rs.next()){
                stat.executeUpdate("UPDATE Maintenance_staff "
                    + "SET ms_fname='"+fname+"', ms_lname='"+lname+"' "
                    + "WHERE emp_id='"+empID+"'");
                stat.executeUpdate("UPDATE Employee "
                    + "SET emp_fname='"+fname+"', emp_lname='"+lname+"', gender='"+gndr+"', address='"+address+"', contact_no='"+contact+"' "
                    + "WHERE nic_no='"+msNIC+"'");
                JOptionPane.showMessageDialog(null, "Successfully updated", "Update",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "No employee in this NIC no..", "Error..",JOptionPane.INFORMATION_MESSAGE);
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        otfn.setText("");
        otln.setText("");
        ot_addr.setText("");
        ot_cntct.setText(""); 
        emid.setText("");
        otid.setText("");
        ot_nic.setText("");
    }//GEN-LAST:event_updtActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        // TODO add your handling code here:
        String gndr="", fname="", lname="", address="", contact="", empID="", msID="";
                        
        try {            
            Statement stat = DataBase.getStatement();
            boolean check=false;
            ResultSet rs = stat.executeQuery("SELECT * FROM Employee WHERE nic_no='"+ot_nic.getText()+"'");
            if(rs.next()){
                empID = rs.getString("emp_id");
                fname = rs.getString("emp_fname");
                lname = rs.getString("emp_lname");
                gndr = rs.getString("gender");
                address = rs.getString("address");
                contact = rs.getString("contact_no");  
                check=true;
            }
            else{                            
                JOptionPane.showMessageDialog(null, "No employee in this NIC no..", "Error..",JOptionPane.INFORMATION_MESSAGE);
                ot_nic.setText("");
            }
            if(check){
                boolean check2=true;
                ResultSet rs1 = stat.executeQuery("SELECT ms_id FROM Maintenance_staff WHERE emp_id='"+empID+"'");
                if(rs1.next()){
                    msID = rs1.getString(1);
                    check2=true;
                }else{
                    check2=false;
                }
                
                if(check2){
                    if(gndr.equals("Male")){
                        ml.setSelected(true);
                    }else{
                        fml.setSelected(true);
                    }
                    otfn.setText(fname);
                    otln.setText(lname);
                    ot_addr.setText(address);
                    ot_cntct.setText(contact); 
                    emid.setText(empID);
                    otid.setText(msID);
                }
                else{
                    JOptionPane.showMessageDialog(null, "This employee is not in maintenance staff..", "Error..",JOptionPane.INFORMATION_MESSAGE);
                    ot_nic.setText("");
                }
                                                              
            }                        
                        
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_srchActionPerformed

    private void ot_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ot_nicKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(ot_nic.getText().length() == 10){
            evt.consume();
        }
    }//GEN-LAST:event_ot_nicKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtStaffReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtStaffReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtStaffReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtStaffReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtStaffReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dlt;
    private javax.swing.JTextField emid;
    private javax.swing.JRadioButton fml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton ml;
    private javax.swing.JTextArea ot_addr;
    private javax.swing.JTextField ot_cntct;
    private javax.swing.JTextField ot_nic;
    private javax.swing.JTextField otfn;
    private javax.swing.JTextField otid;
    private javax.swing.JTextField otln;
    private javax.swing.JButton sbmt;
    private javax.swing.JButton srch;
    private javax.swing.JButton updt;
    // End of variables declaration//GEN-END:variables
}
