/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Sampath
 */
public class PatientReg extends javax.swing.JFrame {

    /**
     * Creates new form PatientReg
     */
    public PatientReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pfn = new javax.swing.JTextField();
        pln = new javax.swing.JTextField();
        p_nic = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_addr = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p_cntact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cnfm_doct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ml = new javax.swing.JRadioButton();
        fml = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        sbmt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        p_age = new javax.swing.JTextField();
        dlt = new javax.swing.JButton();
        updt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        srch = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        pId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cnslt_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 222, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(703, 454));
        jPanel1.setMinimumSize(new java.awt.Dimension(703, 454));
        jPanel1.setPreferredSize(new java.awt.Dimension(703, 454));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Registration Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 610, 40));
        jPanel1.add(pfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 220, 30));
        jPanel1.add(pln, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 220, 30));

        p_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                p_nicKeyTyped(evt);
            }
        });
        jPanel1.add(p_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 30));

        p_addr.setColumns(20);
        p_addr.setRows(5);
        jScrollPane1.setViewportView(p_addr);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 220, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NIC no");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Patient Contact no");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 30));
        jPanel1.add(p_cntact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 30));
        jPanel1.add(cnfm_doct, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 60, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Confirmed doctor ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 130, 30));

        ml.setBackground(new java.awt.Color(227, 222, 222));
        buttonGroup1.add(ml);
        ml.setText("Male");
        jPanel1.add(ml, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        fml.setBackground(new java.awt.Color(227, 222, 222));
        buttonGroup1.add(fml);
        fml.setText("Female");
        jPanel1.add(fml, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, 30));

        sbmt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sbmt.setText("Submit");
        sbmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtActionPerformed(evt);
            }
        });
        jPanel1.add(sbmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 240, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Age");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 30));
        jPanel1.add(p_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 60, 30));

        dlt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dlt.setText("Delete");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        jPanel1.add(dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 170, 40));

        updt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updt.setText("Update");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        jPanel1.add(updt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 170, 40));

        jPanel2.setBackground(new java.awt.Color(227, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        srch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        srch.setText("Search by NIC");
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });
        jPanel2.add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 13, 200, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("patient_id");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 94, 30));
        jPanel2.add(pId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 71, 98, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 220, 120));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Assigned Consultant id");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 150, 30));
        jPanel1.add(cnslt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sbmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtActionPerformed
        // TODO add your handling code:
        
        String gndr = "";
        if(fml.isSelected()){
            gndr="Female";
        }else if(ml.isSelected()){
            gndr = "Male";
        }
        
        String nic = p_nic.getText();
        String lname = pln.getText();
        String fname = pfn.getText();
        
        boolean checkValidity=true;
        
        if(nic.equals("") || lname.equals("") || fname.equals("")){
            checkValidity=false;                
        }
        if(checkValidity){
            try {
                int age = Integer.valueOf(p_age.getText());
                int cnfm_id = Integer.valueOf(cnfm_doct.getText());
                int cnsult_id = Integer.valueOf(cnslt_id.getText());
                
                //String age = p_age.getText();
                Statement stat = DataBase.getStatement();
                stat.executeUpdate("INSERT INTO Patient(patient_fname, patient_lname, age, nic_no, gender, address, contact_no, confirm_doct_id, assigned_consult_id) "
                        + "VALUES('"+fname+"','"+lname+"','"+age+"','"+nic+"','"+gndr+"','"+p_addr.getText()+"','"+p_cntact.getText()+"','"+cnfm_id+"','"+cnsult_id+"')");
                
                JOptionPane.showMessageDialog(null, "New patient registered..", "Submission...",JOptionPane.INFORMATION_MESSAGE);
            }catch(NumberFormatException e1){
                JOptionPane.showMessageDialog(null, "Invalid data type..", "Submission...",JOptionPane.INFORMATION_MESSAGE);
            }catch (Exception e) {
                e.printStackTrace();
            }

            pfn.setText("");
            pln.setText("");
            p_nic.setText("");
            p_addr.setText("");
            p_cntact.setText("");
            cnfm_doct.setText("");
            p_age.setText("");
            cnslt_id.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "You have input data in wrong pattern..", "Validation eEror..",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_sbmtActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        // TODO add your handling code here:
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs1 = stat.executeQuery("SELECT * FROM Patient WHERE nic_no='"+p_nic.getText()+"'");
            
            if(rs1.next()){
                pId.setText(rs1.getString("patient_id"));
                pfn.setText(rs1.getString("patient_fname"));
                pln.setText(rs1.getString("patient_lname")); 
                p_age.setText(rs1.getString("age"));
                p_addr.setText(rs1.getString("address"));
                p_cntact.setText(rs1.getString("contact_no"));
                cnfm_doct.setText(rs1.getString("confirm_doct_id"));
                cnslt_id.setText(rs1.getString("assigned_consult_id"));                
                
                String gndr = rs1.getString("gender");
                if(gndr.equals("Male")){
                    ml.setSelected(true);
                }else if(gndr.equals("Female")){
                    fml.setSelected(true);
                }
            }else{
                JOptionPane.showMessageDialog(null, "There is no patient with this NIC no..", "Error..",JOptionPane.INFORMATION_MESSAGE);
            }
                    
        } catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_srchActionPerformed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        // TODO add your handling code here:
        String gndr = "", pID="";
        boolean check=false;
        if(fml.isSelected()){
            gndr="Female";
        }else if(ml.isSelected()){
            gndr = "Male";
        }
        
        try {
            int age = Integer.valueOf(p_age.getText());
            int cnfm_id = Integer.valueOf(cnfm_doct.getText());
            int cnsult_id = Integer.valueOf(cnslt_id.getText());
            
            Statement stat = DataBase.getStatement();
            ResultSet rs = stat.executeQuery("SELECT patient_id FROM Patient WHERE nic_no='"+p_nic.getText()+"'");
            if(rs.next()){
                pID = rs.getString(1);
                check=true;
            }else{
                JOptionPane.showMessageDialog(null, "This Patient is not registered...\n Cannot update..", "Error...",JOptionPane.INFORMATION_MESSAGE);
            }
            
            if(check){
                stat.executeUpdate("UPDATE Patient "
                    + "SET patient_fname='"+pfn.getText()+"', patient_lname='"+pln.getText()+"', age='"+age+"', nic_no='"+p_nic.getText()+"', gender='"+gndr
                    +"', address='"+p_addr.getText()+"', contact_no='"+p_cntact.getText()+"', confirm_doct_id='"+cnfm_id+"', assigned_consult_id='"+cnsult_id
                    + "' WHERE patient_id='"+pID+"'");
                JOptionPane.showMessageDialog(null, "Updated succesfully..", "Update...",JOptionPane.INFORMATION_MESSAGE);
            }
                        
        }catch(NumberFormatException e1){
                JOptionPane.showMessageDialog(null, "Invalid data type..", "Submission error...",JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e) {
            e.printStackTrace();
        }
    
        pfn.setText("");
        pln.setText("");
        p_nic.setText("");
        p_addr.setText("");
        p_cntact.setText("");
        cnfm_doct.setText("");
        p_age.setText("");
        cnslt_id.setText("");
    }//GEN-LAST:event_updtActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
        String nic=p_nic.getText(), pID="";
        boolean check=true;
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs = stat.executeQuery("SELECT patient_id FROM Patient WHERE nic_no='"+nic+"'");
            if(rs.next()){
                pID = rs.getString(1);
            }else{
                JOptionPane.showMessageDialog(null, "No patient with this nic_no..", "Error...",JOptionPane.INFORMATION_MESSAGE);
                check=false;
            }
            if(check){
                ResultSet rs1 = stat.executeQuery("SELECT * FROM Admission WHERE patient_id='"+pID+"'");
                if(rs1.next()){
                    JOptionPane.showMessageDialog(null, " This patient is an admitted one \n So cannot deleted..", "Error...",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    stat.executeUpdate("DELETE FROM Patient WHERE nic_no='"+nic+"'");
                    JOptionPane.showMessageDialog(null, "Successfully deleted one patient..", "Error...",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_dltActionPerformed

    private void p_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_nicKeyTyped
        // TODO add your handling code here:
        char a = evt.getKeyChar();
        if(p_nic.getText().length() == 10){
            evt.consume();
        }
    }//GEN-LAST:event_p_nicKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cnfm_doct;
    private javax.swing.JTextField cnslt_id;
    private javax.swing.JButton dlt;
    private javax.swing.JRadioButton fml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton ml;
    private javax.swing.JTextField pId;
    private javax.swing.JTextArea p_addr;
    private javax.swing.JTextField p_age;
    private javax.swing.JTextField p_cntact;
    private javax.swing.JTextField p_nic;
    private javax.swing.JTextField pfn;
    private javax.swing.JTextField pln;
    private javax.swing.JButton sbmt;
    private javax.swing.JButton srch;
    private javax.swing.JButton updt;
    // End of variables declaration//GEN-END:variables
}
