/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import javax.swing.JOptionPane;

/**
 *
 * @author Sampath
 */
public class Selection_admin extends javax.swing.JFrame {

    /**
     * Creates new form Selection1
     */
    public Selection_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        wr = new javax.swing.JButton();
        dr = new javax.swing.JButton();
        pr = new javax.swing.JButton();
        nr = new javax.swing.JButton();
        oth_s = new javax.swing.JButton();
        panel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        pwchng = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(380, 320));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wr.setText("Ward");
        wr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrActionPerformed(evt);
            }
        });
        jPanel2.add(wr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 150, 30));

        dr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dr.setText("Doctors");
        dr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drActionPerformed(evt);
            }
        });
        jPanel2.add(dr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 150, 30));

        pr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pr.setText("Patient");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        jPanel2.add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 150, 30));

        nr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nr.setText("Nurse");
        nr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrActionPerformed(evt);
            }
        });
        jPanel2.add(nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 150, 30));

        oth_s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oth_s.setText("Other Staff");
        oth_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oth_sActionPerformed(evt);
            }
        });
        jPanel2.add(oth_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 150, 30));

        panel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/download.jpg"))); // NOI18N
        jPanel2.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 250));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), java.awt.Color.lightGray));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 150, 50));

        pwchng.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwchng.setText("Change password");
        pwchng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwchngActionPerformed(evt);
            }
        });
        jPanel1.add(pwchng, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 156, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 380, 70));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Services");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrActionPerformed
        // TODO add your handling code here:
        WardReg w1 = new WardReg();
        w1.setVisible(true);
    }//GEN-LAST:event_wrActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        // TODO add your handling code here:
        PatientReg pr1 = new PatientReg();
        pr1.setVisible(true);
    }//GEN-LAST:event_prActionPerformed

    private void drActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drActionPerformed
        // TODO add your handling code here:
        DoctorReg d1 = new DoctorReg();
        d1.setVisible(true);
    }//GEN-LAST:event_drActionPerformed

    private void nrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrActionPerformed
        // TODO add your handling code here:
        NurseReg nr1 = new NurseReg();
        nr1.setVisible(true);
    }//GEN-LAST:event_nrActionPerformed

    private void oth_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oth_sActionPerformed
        // TODO add your handling code here:
        OtStaffReg otsr = new OtStaffReg();
        otsr.setVisible(true);
    }//GEN-LAST:event_oth_sActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JOptionPane.showMessageDialog(null, "Successfully loggedout by admin...", "<<<<  Logout  >>>>",JOptionPane.INFORMATION_MESSAGE);
        Login.login l =new Login.login();
        l.setVisible(true);        
    }//GEN-LAST:event_logoutActionPerformed

    private void pwchngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwchngActionPerformed
        // TODO add your handling code here:
        Login.PasswordChange pc = new Login.PasswordChange();
        pc.setVisible(true);                
    }//GEN-LAST:event_pwchngActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Service s = new Service();
        s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selection_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selection_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selection_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selection_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selection_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dr;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    private javax.swing.JButton nr;
    private javax.swing.JButton oth_s;
    private javax.swing.JLabel panel2;
    private javax.swing.JButton pr;
    private javax.swing.JButton pwchng;
    private javax.swing.JButton wr;
    // End of variables declaration//GEN-END:variables
}
