/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sampath
 */
public class Service extends javax.swing.JFrame {

    /**
     * Creates new form Service
     */
    public Service() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        snm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dscr = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        wrd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        val = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tst = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        trt = new javax.swing.JRadioButton();
        srch = new javax.swing.JButton();
        srvID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sbmt = new javax.swing.JButton();
        dlt = new javax.swing.JButton();
        updt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 222, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(534, 315));
        jPanel1.setMinimumSize(new java.awt.Dimension(534, 315));
        jPanel1.setPreferredSize(new java.awt.Dimension(534, 315));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Service Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 310, 30));

        jLabel2.setText("Service Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 80, 30));

        jLabel3.setText("Description");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 30));
        jPanel1.add(snm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, 30));

        dscr.setColumns(20);
        dscr.setRows(5);
        jScrollPane1.setViewportView(dscr);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 200, -1));

        jLabel4.setText("Ward ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, 30));
        jPanel1.add(wrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, 30));

        jLabel6.setText("Value");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 30));
        jPanel1.add(val, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 80, 30));

        jPanel2.setBackground(new java.awt.Color(227, 222, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tst.setBackground(new java.awt.Color(227, 222, 222));
        buttonGroup1.add(tst);
        tst.setText("Test");
        jPanel2.add(tst, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Type");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        trt.setBackground(new java.awt.Color(227, 222, 222));
        buttonGroup1.add(trt);
        trt.setText("Treatment");
        jPanel2.add(trt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        srch.setText("Search");
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });
        jPanel2.add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));
        jPanel2.add(srvID, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 110, 100, 30));

        jLabel8.setText("Service id");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 150));

        sbmt.setText("Submit");
        sbmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtActionPerformed(evt);
            }
        });
        jPanel1.add(sbmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 150, 30));

        dlt.setText("Delete");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        jPanel1.add(dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 70, 30));

        updt.setText("Update");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        jPanel1.add(updt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sbmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtActionPerformed
        // TODO add your handling code here:       
               
        String S_name = snm.getText();
        String ward  = wrd.getText();
        String descr = dscr.getText();
        String value = val.getText();
        
        
        String type="";
        if(trt.isSelected()){
            type = "Treatment";
            trt.setSelected(false);
        }else if(tst.isSelected()){
            type = "Test";
            tst.setSelected(false);
        }
        
        boolean checkValidity = true;
        try {
            int wdid = Integer.valueOf(wrd.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid data type..", "Submission...",JOptionPane.INFORMATION_MESSAGE);
            checkValidity=false;
        }
        
        if(S_name.equals("") || ward.equals("")){
            checkValidity=false;
        }
        
        if(checkValidity){
            Controller.ServiceReg_con c = new Controller.ServiceReg_con();
            c.SubmitBtn(S_name, ward, descr, value, type);

            JOptionPane.showMessageDialog(null, "Service added successfully..", "Submission..",JOptionPane.INFORMATION_MESSAGE);

            snm.setText("");
            wrd.setText("");
            dscr.setText("");
            val.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Some inputs are in wrong manner", "Validation error..",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_sbmtActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        // TODO add your handling code here:
        String srvName = snm.getText();
        String wrdid = wrd.getText();
                
        Controller.ServiceReg_con cs = new Controller.ServiceReg_con();
        
        boolean whatNxt = cs.checkNum(srvName);
        if(whatNxt){
            
            try {
                Statement stat = Admin.DataBase.getStatement();
                ResultSet rs = stat.executeQuery("SELECT * FROM Service WHERE service_name='"+srvName+"'");
                while(rs.next()){
                    String type = rs.getString("serv_type");
                    srvID.setText(rs.getString("serve_id"));
                    wrd.setText(rs.getString("ward_id"));
                    val.setText(rs.getString("value"));
                    dscr.setText(rs.getString("description"));
                    if(type.equals("Test")){
                        tst.setSelected(true);
                    }else if(type.equals("Treatment")){
                        trt.setSelected(true);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }else{
            if(wrdid.equals("")){
                JOptionPane.showMessageDialog(null, "This service is in many wards.. \n You haven't provided ward id", "Input error",JOptionPane.INFORMATION_MESSAGE);
            }else{
                try {
                    Statement stat = Admin.DataBase.getStatement();
                    ResultSet rs = stat.executeQuery("SELECT * FROM Service WHERE service_name='"+srvName+"' AND ward_id='"+wrdid+"'");
                    
                    if(rs.next()){
                        srvID.setText(rs.getString("serve_id"));
                        val.setText(rs.getString("value"));
                        dscr.setText(rs.getString("description"));
                        String type = rs.getString("serv_type");
                        if(type.equals("Test")){
                            tst.setSelected(true);
                        }else if(type.equals("Treatment")){
                            trt.setSelected(true);
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "No service in that name.", "Input error",JOptionPane.INFORMATION_MESSAGE);
                    }
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }            
        }        
        
    }//GEN-LAST:event_srchActionPerformed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        // TODO add your handling code here:
        
        int ward=0;
        String S_name = snm.getText();
        String descr = dscr.getText();
        String value = val.getText();
        String serv_id = srvID.getText();
        
        String type="";
        boolean checkValidity=true;
        
        if(trt.isSelected()){
            type = "Treatment";
            trt.setSelected(false);
        }else if(tst.isSelected()){
            type = "Test";
            tst.setSelected(false);
        }
        try {
            ward = Integer.valueOf(wrd.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid data type..", "Submission...",JOptionPane.INFORMATION_MESSAGE);
            checkValidity=false;
        }
        String wardno = Integer.toString(ward);
        Controller.ServiceReg_con c = new Controller.ServiceReg_con();
        
        if(checkValidity){
            c.UpdateBtn(S_name, wardno, descr, value, type, serv_id);
                
            snm.setText("");
            wrd.setText("");
            dscr.setText("");
            val.setText("");
            srvID.setText("");
        }
        
    }//GEN-LAST:event_updtActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
        String srvName = snm.getText();
        String wrdid = wrd.getText();
                
        Controller.ServiceReg_con cs = new Controller.ServiceReg_con();
        
        boolean whatNxt = cs.checkNum(srvName);
        if(whatNxt){
            cs.dltBtn(srvName);
        }else{
            if(wrdid.equals("")){
                JOptionPane.showMessageDialog(null, "This service is in many wards.. \n You haven't provided ward id", "Input error",JOptionPane.INFORMATION_MESSAGE);
            }else{
                cs.dltBtn(srvName, wrdid);
            }
        }
    }//GEN-LAST:event_dltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dlt;
    private javax.swing.JTextArea dscr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sbmt;
    private javax.swing.JTextField snm;
    private javax.swing.JButton srch;
    private javax.swing.JTextField srvID;
    private javax.swing.JRadioButton trt;
    private javax.swing.JRadioButton tst;
    private javax.swing.JButton updt;
    private javax.swing.JTextField val;
    private javax.swing.JTextField wrd;
    // End of variables declaration//GEN-END:variables
}
