/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sampath
 */
public class WardReg extends javax.swing.JFrame {

    /**
     * Creates new form WardReg
     */
    public WardReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        hd_name = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        wd_nm = new javax.swing.JTextField();
        hdoct_nm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        bd_no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sbmitBtn = new javax.swing.JButton();
        wd_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        srch1 = new javax.swing.JButton();
        srch2 = new javax.swing.JButton();
        updt = new javax.swing.JButton();
        dlt = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        hd_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hd_nameActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(227, 222, 222));
        jPanel1.setMaximumSize(new java.awt.Dimension(545, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(545, 440));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(545, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ward Registration / Details Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 260, 40));

        jLabel2.setBackground(new java.awt.Color(255, 118, 28));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Ward Id (Auto assigned)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 140, 30));
        jPanel1.add(wd_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 30));
        jPanel1.add(hdoct_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 180, 30));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 320, 110));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Head Doctor of Ward");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 30));
        jPanel1.add(bd_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("No of Beds");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Description");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 80, 40));

        sbmitBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sbmitBtn.setText("Submit");
        sbmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(sbmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 130, 40));
        jPanel1.add(wd_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 70, 30));

        jLabel6.setBackground(new java.awt.Color(255, 118, 28));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Ward Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, 30));

        srch1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        srch1.setText("Search by Name");
        srch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch1ActionPerformed(evt);
            }
        });
        jPanel1.add(srch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 130, 30));

        srch2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        srch2.setText("Search by Id");
        srch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srch2ActionPerformed(evt);
            }
        });
        jPanel1.add(srch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 130, 30));

        updt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updt.setText("Update");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        jPanel1.add(updt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 130, 40));

        dlt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dlt.setText("Delete");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        jPanel1.add(dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hd_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hd_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hd_nameActionPerformed

    private void sbmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmitBtnActionPerformed
        // TODO add your handling code here
        String wrdNM=wd_nm.getText();
        int bdno=0;
        boolean checkValidity=true;
        if(wrdNM.equals("")){
            checkValidity=false;
        }
        if(checkValidity){
            try {
                bdno = Integer.valueOf(bd_no.getText());
                Statement stat = DataBase.getStatement();
                stat.executeUpdate("INSERT INTO Ward (ward_name, head_doct_name, no_of_beds, description) "
                        + "VALUES('"+wrdNM+"','"+hdoct_nm.getText()+"','"+bdno+"','"+desc.getText()+"')");
            } catch(NumberFormatException e1){
                JOptionPane.showMessageDialog(null, "Invalid data type..", "Submission...",JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Successfully added new Ward..", "Notice..",JOptionPane.INFORMATION_MESSAGE);

            wd_nm.setText("");
            wd_id.setText("");
            hdoct_nm.setText("");
            bd_no.setText("");
            desc.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "You have input data in wrong pattern..", "Validation Error..",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_sbmitBtnActionPerformed

    private void srch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch1ActionPerformed
        // TODO add your handling code here:
        String wdno="", bed_no="", dscrpt="", hdDoctno="";
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs1 = stat.executeQuery("SELECT * FROM Ward WHERE ward_name='"+wd_nm.getText()+"'");
            
            if(!(rs1.next())){
                JOptionPane.showMessageDialog(null, "Ward name you entered is wrong...", "Error..",JOptionPane.INFORMATION_MESSAGE);
                wd_nm.setText("");
            }
            else{
                wdno=rs1.getString("ward_id");
                bed_no = rs1.getString("no_of_beds");
                dscrpt = rs1.getString("description");
                hdDoctno = rs1.getString("head_doct_name");
                                
                wd_id.setText(wdno);
                hdoct_nm.setText(hdDoctno);
                bd_no.setText(bed_no);
                desc.setText(dscrpt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }            
    }//GEN-LAST:event_srch1ActionPerformed

    private void srch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srch2ActionPerformed
        // TODO add your handling code here:
        String wdnm="", bed_no="", dscrpt="", hdDoctno="";
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs1 = stat.executeQuery("SELECT * FROM Ward WHERE ward_id='"+wd_id.getText()+"'");
            
            if(!(rs1.next())){
                JOptionPane.showMessageDialog(null, "Ward Id you entered is wrong...", "Error..",JOptionPane.INFORMATION_MESSAGE);
                wd_id.setText("");
            }
            else{                
                wdnm=rs1.getString("ward_name");
                bed_no = rs1.getString("no_of_beds");
                dscrpt = rs1.getString("description");
                hdDoctno = rs1.getString("head_doct_name");
                                
                wd_nm.setText(wdnm);
                hdoct_nm.setText(hdDoctno);
                bd_no.setText(bed_no);
                desc.setText(dscrpt);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }            
    }//GEN-LAST:event_srch2ActionPerformed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        // TODO add your handling code here:
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs1 = stat.executeQuery("SELECT * FROM Ward WHERE ward_name='"+wd_nm.getText()+"'");
            
            boolean check=true;
            String wardId = "";
            int bdno= Integer.valueOf(bd_no.getText());
            
            if(rs1.next()){
                wardId = rs1.getString("ward_id");
            }
            else if(!(rs1.next())){
                JOptionPane.showMessageDialog(null, "There is no query in table in that name cannot update..", "Error..",JOptionPane.INFORMATION_MESSAGE);
                check=false;
            }
            
            if(check){
                stat.executeUpdate("UPDATE Ward "
                        +         "SET ward_name='"+wd_nm.getText()+"', head_doct_name='"+hdoct_nm.getText()+"', no_of_beds='"+bdno+"', description='" +desc.getText()
                        +         "' WHERE ward_id='"+wardId+"'");
                JOptionPane.showMessageDialog(null, "Succesfully updated...", "Update..",JOptionPane.INFORMATION_MESSAGE);
            }
                                    
            wd_nm.setText("");
            wd_id.setText("");
            hdoct_nm.setText("");
            bd_no.setText("");
            desc.setText("");
                        
        } catch(NumberFormatException e1){
                JOptionPane.showMessageDialog(null, "Invalid data type..", "Error...",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updtActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
        try {
            Statement stat = DataBase.getStatement();
            ResultSet rs1 = stat.executeQuery("SELECT * FROM Ward WHERE ward_name='"+wd_nm.getText()+"'");
            
            boolean check=true;
            String wardId = "";
            
            if(rs1.next()){
                wardId = rs1.getString("ward_id");
            }
            else if(!(rs1.next())){
                JOptionPane.showMessageDialog(null, "There is no query in table in that name.. \n Cannot perform delete..", "Error..",JOptionPane.INFORMATION_MESSAGE);
                check=false;
            }
            if(check){
                JOptionPane.showMessageDialog(null, "Sucessfully deleted relevant data from DB..", "Deletion..",JOptionPane.INFORMATION_MESSAGE);
                stat.execute("DELETE FROM Ward WHERE ward_id='"+wardId+"'");
            }
            wd_nm.setText("");
            wd_id.setText("");
            hdoct_nm.setText("");
            bd_no.setText("");
            desc.setText("");
            
        }catch (Exception e) {
            e.printStackTrace();
        }        
    }//GEN-LAST:event_dltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WardReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WardReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WardReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WardReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WardReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bd_no;
    private javax.swing.JTextArea desc;
    private javax.swing.JButton dlt;
    private javax.swing.JTextField hd_name;
    private javax.swing.JTextField hdoct_nm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton sbmitBtn;
    private javax.swing.JButton srch1;
    private javax.swing.JButton srch2;
    private javax.swing.JButton updt;
    private javax.swing.JTextField wd_id;
    private javax.swing.JTextField wd_nm;
    // End of variables declaration//GEN-END:variables
}
